# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
---
include:
  - board: xiao_ble//zmk
    shield: testing_board_matrix
    snippet: zmk-usb-logging
    artifact-name: testing_board_matrix_with_logging
  - board: xiao_ble//zmk
    shield: settings_reset
    artifact-name: xiao_settings_reset
  - board: xiao_ble//zmk
    shield: testing_board_matrix
    artifact-name: testing_board_matrix
  - board: xiao_ble//zmk
    shield: testing_board_charlieplexing
    artifact-name: testing_board_charlieplexing
